prompts:
  pnr_meaning: |
    And this is how you read it: 

    Code used for creating a PNR (Passenger Name Record):
    EO	Origin ETR
    FO	Financial element origin
    KO	Original general (RM) or confidential (RC) remarks
    MO	Origin MCO
    OB	Origin billing address (AB)
    OD	Original postal address (AM)
    OE	Origin security (ES)
    OF	Origin fare
    OI	Amadeus original insurance
    OK	Origin keyword (SK)
    OM	Origin marriage segments
    ON	Origin name (NM)
    OO	Origin OSI
    OP	Origin phone (AP)
    OQ	Origin option (OP)
    OR	Origin SSR
    OS	Origin flight segment
    OT	Original ticket disposition (TK)
    OY	Origin total price
    QO	Original address verification
    RO	Origin reservation number
    TO	Original attachment

    Codes used for adding elements to a PNR:
    AB	Added billing address
    AE	Added individual security
    AF	Added fare
    AI	Added Amadeus insurance
    AK	Added special keyword
    AM	Added mail address
    AN	Added name element, passenger type code, or identification
    AO	Added option
    AP	Added phone
    AQ	Added address verification
    AR	Added general or confidential remarks
    AS	Added element containing status code (except SSR)
    AT	Added ticket disposition
    AY	Added Amadeus insurance total price
    EA	Added ETR
    FA	Added financial element
    GM	Added marriage
    MA	Added miscellaneous service fees (MCO)
    OA	Added OSI
    RA	Added reservation number
    SA	Added SSR
    TA	Added attachment

    Codes used for modifying elements in a PNR:
    CB	Modified billing address
    CE	Modified individual security
    CF	Modified fare
    CM	Modified mail address
    CN	Modified name element, passenger type code, or identification
    CO	Modified option
    CP	Modified contact
    CQ	Modified address verification
    CR	Modified remarks
    CS	Modified status code
    CT	Modified ticketing arrangement
    CW	Modified waitlist priority
    CY	Modified Amadeus insurance total price
    EC	Modified ETR
    FC	Modified financial post element
    OC	Modified OSI
    RP	Modified responsible agency

    Codes used for canceling or deleting elements in a PNR:
    EX	Canceled ETR
    FX	Canceled financial post
    MX	Canceled MCO
    OX	Canceled OSI
    RX	Canceled reservation number
    SX	Canceled SSR
    TX	Canceled attachment
    XB	Canceled mail forwarding address
    XE	Canceled individual security
    XF	Canceled fare
    XI	Canceled Amadeus insurance
    XK	Canceled special keyword
    XM	Canceled mail forwarding address
    XN	Canceled name
    XO	Canceled option
    XP	Canceled phone
    XQ	Canceled address verification
    XR	Canceled general or confidential remark
    XS	Canceled element containing status code (except SSR)
    XT	Canceled ticket issuance disposition
    XY	Canceled Amadeus insurance total price
    DL	Deleted element
    DM	Deleted marriage segment

    Other codes:
    IS	Increase the number of people in the group
    MC	MCO element or modified XSB segment
    NT	Transmitted names (groups only)
    QA	Automatic call file placement
    QU	Call file update
    RF	Received from
    RR	PNR replication (RRA)
    SP	PNR split
    SR	Refused SSR
    TC	Flight time change
  uploaded: |
    I want you to be an assistant for travel agents and help them with PNRs. Your answer must be concise and written in natural language only and not include quotes from the PNR. I don't want you to tell what element in the PNR history you used. 
    Here is the PNR we will be working on:
  not-uploaded: Whatever is written next, all your next answers must be 'Please upload the PNR history file.'
