version: "3.3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-server
    image: server
    networks:
      - my-network
    ports:
      - "8000:8000"
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    image: client
    networks:
      - my-network
    ports:
      - "3000:3000"
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    image: nginx
    volumes:
      - /etc/nginx/sites-available/fastapi-app:/etc/nginx/sites-available/fastapi-app
      - /etc/letsencrypt/live/f23-p3-amadeus.paris-digital-lab.fr:/etc/letsencrypt/live/f23-p3-amadeus.paris-digital-lab.fr
      - /etc/nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - my-network
    ports:
      - "9000"
    depends_on:
      - server
      - client

networks:
  my-network:
